spring:
  redis:
    host: 192.168.233.216
    port: 6379
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    sentinel:
      transport:
        dashboard: localhost:8082
        port: 8719
    alicloud:
      access-key: LTAI5tSpBk5kS3HV8UDXTPjY
      secret-key: DA1cYnfbbQNpRVMXOPIif0TMp7DtoO
      oss:
        endpoint: oss-cn-guangzhou.aliyuncs.com
        bucketName: zjw-guli-mall
  application:
    name: guli-mall-thirdparty-service
server:
  port: 12000

management:
  endpoints:
    web:
      exposure:
        include: '*'
